### PR TITLE
Update to v1.5

### PR DESCRIPTION
**Pull request by joker314**
All v1.5 milestone issues have been closed. Let's update the extension!

### CODE REVIEW

**Comment by joker314** [comment]
**If this pull request is merged, it will move the contents of the develop branch into the master branch**

**Comment by DeleteThisAcount** [comment]
W o a h  T e c h n o l o g y

**Comment by DeleteThisAcount** [comment]
Do it now!!!

**Comment by radioblahaj** [comment]
UPDATEW!!!!

**Comment by kickofline** [comment]
UPDATE!!!

**Comment by DeleteThisAcount** [comment]
You guys missed it!! Some people's Halloween are almost ovrr!

**Comment by DeleteThisAcount** [comment]
Too late!

**Pull request merged**
