### PR TITLE
[NOMERGE] Notifications when your friends go online

### PR DESCRIPTION
**Pull request by joker314**
[NOMERGE] Do not merge this, as it is incomplete. Instead, assist in the code if you can.

- [X] Background script added to manifest.json
- [X] Message passing to communicate new/del friends
- [X] Verify the 10 person limit
- [X] Comment code well
- [ ] Consider using chrome storage
- [ ] Get rich notification permission in manifest.json
- [ ] Implement notifications
- [ ] When you click the notification, it should take you to their profile
- [ ] To the standard content script, add a button next to each profile ("Add friend", "Remove friend")
- [ ] Render any errors to the client
- [ ] Consider using `chrome.storage` instead of `localStorage`

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Looks very good! 👍

**Comment by joker314** [comment]
We need to decide if we want to use chrome storage (I accidentally put it on the list twice). Right now, we are using complicated message passing (like the broadcast block) to send stuff from the localStorage in Scratch to that of the extension.

A better way would be to add a "storage" permission to the manifest.json, but then be able to just use `chrome.storage.sync.set()` and `chrome.storage.sync.get()` which would just be SO much easier and more readable.

**Comment by JordanB-1337** [comment]
because everyone uses chrome.

**Comment by joker314** [comment]
@JordanB-1337 you bring up an excellent point, but this is a *chrome* extension at the current time. Any message passing will be different on a per-browser basis so unfortunately we are going to use chrome storage.

Don't worry,  we will be adding support for other languages

**Review by WorldLanguages — COMMENTED** [review]
I think that if we add "strorage" as a permission isOnline will be disabled because it needs more permissions... maybe as an optional permission and asking for it somehow?

**Comment by WorldLanguages** [comment]
I'm not sure if, if we add the storage permission, it will be disabled for all current users... Chrome doesn't disable extensions for all new permissions.

**Comment by joker314** [comment]
Well, in that case, we stick to this method. But then we also need a `notification` permission -- unless you plan to send notifications from `code.js`. But if you do that, then if Scratch is closed it won't work. So what do we do?

**Comment by WorldLanguages** [comment]
We should add notifications as an optional permission and ask for permission for it later.

**Comment by WorldLanguages** [comment]
Update: Looks like we don't need to require permission for storage. So the only optional permissions we'll need to ask if the user enables friend notifications are: "background" and "notifications" because they display warnings and current isOnline users would have the extension disabled

**Comment by WorldLanguages** [comment]
By the way - what do you think if we only notify users if they have a scratch tab open?

**Comment by joker314** [comment]
We.. could do that I suppose, yeah

**Comment by joker314** [comment]
closinng for now

**Pull request closed without merging**
