### PR TITLE
Update 2

### PR DESCRIPTION
**Pull request by joker314**
This looks ready

### CODE REVIEW

**Comment by WorldLanguages** [comment]
I added:

-Message filtering
-Error telling on non scratch-www pages
-Added some semicolons

There seems to be a problem with multi account verification :(

**Comment by joker314** [comment]
Yes, I noticed. Well, I'm working on it! Let's be consistent with semicolons -- in JavaScript they are optional but avoid ambiguity. :)

**Comment by ed-cooper** [comment]
> in JavaScript they are optional

This made me cry

**Comment by joker314** [comment]
These are the test cases for multi-user account verification. To pass, one should inspect the localStorage values of `iOuser`, `iOkey` (both should be null), and `iOaccounts`. One should monitor XMLHttpRequests to ensure that the correct username and key is being used.

- [x] Installing the new version autocorrects all the values
- [x] Clear all values and try setting up your isOnline account with the new version
- [x] Try logging in with a different account
- [x] Register the new account
- [x] See if both accounts work correctly

**Comment by joker314** [comment]
@WorldLanguages I think I got multi-account verification going :tada:

**Comment by WorldLanguages** [comment]
Things I changed:

- Errors on try{} are now only logged if it's not a username detecting problem because in scratch-www
- Added animations to verification
- Remove bold from status selecting on own profile
- Remove text shadow on the isonline crown users

**Comment by joker314** [comment]
You need to test:

- [x] Updating the extension from `iOuser` and `iOkey` into `iOaccounts`;
- [x] Verifying your very own account;
- [x] Verifying a second account;
- [x] Re-verifying an account.

Once these things are tested, we should be good to go!

**Comment by joker314** [comment]
Are we ready?

**Pull request merged**
