### PR TITLE
last time i checked

### PR DESCRIPTION
**Pull request by DeleteThisAcount**
cookies were cookies and pumpkins were spooky
(fixes weird naming glitch with pumpkins)

### CODE REVIEW

**Comment by Sheshank-s** [comment]
Can you please make the name more appropriate, like "isOnline Pumpkin"

**Comment by DeleteThisAcount** [comment]
awww ok

**Comment by Sheshank-s** [comment]
I would be happy to merge this, but I don't have write access to the new repo @WorldLanguages Can you give me write access?

**Comment by WorldLanguages** [comment]
Hmm, that pumpkin shouldn't even be there. lol.

**Comment by DeleteThisAcount** [comment]
NO, NO, NOOO MY PUMKINNNNN!!!

**Pull request closed without merging**
