### PR TITLE
v1.5.2

### PR DESCRIPTION
**Pull request by WorldLanguages**
- [x] Better French translation
- [ ] Get Japanese strings localized
- [x] Tell crown users to change the link
- [x] If Scratch was closed, and popup was open when it was open, hide friends completely
- [x] Popup footer (Credits | Scratch account | Review isOnline in the extension store | Update blog<br>Verify a Scratch account | Source on GitHub | Privacy Policy | Uninstall isOnline)
- [x] Credits page
- [ ] Messages related to isOnline verification on popup
- [ ] Un-localize strings that aren't used anymore

Note: this update won't send you to the update blog.

### CODE REVIEW

**Review by radioblahaj — CHANGES_REQUESTED** [review]
Conflicts in the Program.  👍

**Comment by petabyt** [comment]
Idea: users could be able to put _ status _ in their signature and it would appear as if the signature's owner if online or offline.

**Comment by DeleteThisAcount** [comment]
Replace ** with. iO

**Comment by kyleplo** [comment]
Isonline is down! #61

**Pull request closed without merging**
