### PR TITLE
Completed | Add LAST SEEN field to offline statuses

### PR DESCRIPTION
**Pull request by joker314**
Based on a suggestion on the isOnlineV2 suggestions thread ([link to post](https://scratch.mit.edu/discuss/post/2597654/))

ℹ️ Code is fully complete, testing is partially complete, the Scratch Team has not reviewed.
:warning: A test has failed, please don't merge until this issue is solved.

Tests:

- [x] Should not change the way other statuses behave
- [x] When you hover over an offline status, you should see a "Last seen" message
- [x] Test for things on the same day
- [ ] Test for things yesterday
- [x] Test for things even earlier
- [ ] ST review

Once you've done these tests, we can safely merge.

### CODE REVIEW

**Comment by ed-cooper** [comment]
When someone has been offline for an extended period of time, instead of displaying a date and time, something like "Last seen 3 months ago", "Last seen 1 year ago", etc. would be more appropriate imo

Also, are times in the correct timezone for the user viewing the extension? Timestamps from the server are in UTC

**Comment by joker314** [comment]
Timezones should be fine, but that's in theory: in practice, I have absolutely no idea. I guess I could test by changing my system time up. I see your opinion on less-specific times, but at the moment, with the extension being very recent, I think people would prefer accuracy. Especially since brevity doesn't matter because it's not visible on the screen unless you willingly hover. Idk, we need a third opinion.

If you would like to verify the timezone thing, then install the `code.js` as a userscript (after adding the correct userscript header comments at the top) and see if it works. You are in the UK, just like me, which is in a UTC+1 timezone, so any differences should be visible.

**Comment by joker314** [comment]
Uh oh: https://scratch.mit.edu/users/DeleteThisAcount/ this user is showing an incorrect date. It should be in `YYYY-MM-DD`

**Comment by ed-cooper** [comment]
Well, you can still keep full accuracy for when people have only recently gone offline, but after 1 week, the time doesn't matter, and after 1 month, the date doesn't either

**Comment by joker314** [comment]
Hmm well I suppose you are right

**Comment by ed-cooper** [comment]
Heads up: some users may have signed up believing that it won't display how long ago they were online (ie. they might not want this feature)

The data is already (semi) visible anyway so I'd say that this case can be ignored. Otherwise, setting an optional flag would require some changes on the server side to also store and report that value.

**Comment by joker314** [comment]
That is true. We could make it a feature that you have to turn on if you are willing to add more fields to the db?

___________

Can you check, when was the last time @DeleteThisAccount was online according to the timestamp (I can't be bothered to go through the trouble of finding my key)

**Comment by ed-cooper** [comment]
Delete this account timestamp:
1493461174
Saturday 29th April 2017 10:19:34 AM UTC

**Comment by joker314** [comment]
Aha then everything works!

**Comment by ed-cooper** [comment]
It is possible to add more fields to the DB, but then that's more API designing with more scripts and validation

**Comment by joker314** [comment]
Okay, well, we will leave this as an outstanding PR while further testing happens. Once all of that stuff is done, we will sort out conflicts and decide whether to merge

**Pull request closed without merging**
